### PR TITLE
fix: filter for correct usage/usagePage when finding xkeys devices

### LINKED ISSUE #92: Intermittent "NotAllowedError: Failed to write the report." on Chrome v115+
The following uncaught exception (or promise rejection, not sure) `"NotAllowedError: Failed to write the report."` gets thrown from within function `setupXkeysPanel`.

On Chrome versions 117+ (tested on 117, 118, 120), this happens consistently until Chrome is restarted* ( can use chrome://restart ). *The issue gets resolved only after a random number of Chrome restarts and sometimes requiring XKeys to be replugged. The issue can then be reintroduced after a certain random number of Chrome restarts again.

~~The issue is never reproduced on Chrome v115 and below.~~ Chrome v116 behaviour is untested.

In Chrome device log ( chrome://device-log/ ) I see either one of these 2 errors when the issue occurs when calling setupXkeysPanel:
- `Output report buffer too long (36 > 2).`
- `This device does not support output reports.`

Reproduced with:
- XKeys: vendorId=1523, productId=1089, name='XK-80 HID'

Any ideas?

### PR DESCRIPTION
**Pull request by Julusian**
fixes #92

The filtering might be overly strict, and needs to be verified on windows and macos to ensure the required properties are defined.

Tested with a XK24 and XK12-Jog

### CODE REVIEW

**Comment by nytamin** [comment]
Hey @michaelhatPIengineering !
This PR basically adds the filter below (for browser WebHID only):

```typescript
function isValidXkeysUsage(device: HIDDevice): boolean {
	return !!device.collections.find(
		(collection) => collection.type === 1 && collection.usage === 1 && collection.usagePage === 12
	)
}
```

Does this filter look reasonable to you? Do you think we should go ahead and merge this fix right away or would you like to test it with various devices first? (I could prepare a test script for you)

**Comment by michaelhatPIengineering** [comment]
Johan,

To 100% and to future proof this, we should add   && collection.writelength > 20

or what ever the way to see the write length of the "device"

There are some Multi-media devices that also use page 12 so we always check both.

Also, this problem is not just a browser problem, all other OSs could change how they enumerate and would not be out of spec.

So, this filter should be added to all.

MHH

________________________________

**Comment by michaelhatPIengineering** [comment]
We are checking on how this works with all our device descriptors.

A test script might be good.


________________________________

**Comment by KhangxLi** [comment]
it seems like the fix worked on Mac, but not on Windows

**Comment by KhangxLi** [comment]
looks like `collection.type === 0` for XKeys XK-80 on Windows

**Comment by michaelhatPIengineering** [comment]
I reviewed with our firmware engineer; she recommends:

filter on:

VID
PID
Usage page 12
write length > 20

to get the "device" supported by this lib.

other things are redundant or not consistent over all OSs

________________________________

**Comment by Julusian** [comment]
I have stripped out some of the conditions, and left it checking `usagePage` and `vendorId`.
It is validating the productId later, so I don't think it is necessary to do at this early stage, especially as the user prompt isnt doing a filter on productId.

I haven't added a writeLength check, as doing so requires digging deeply into multiple layers of arrays and objects and that makes me a little uneasy about the reliability of doing so. Although each of linux, macos and windows did produce what appeared to be the same data for it:

image

**Comment by michaelhatPIengineering** [comment]
We have found that writeLenght is important to avoid confusion with multi-media which is also the same usage page.

________________________________

**Comment by Julusian** [comment]
ok, I have added that check. The function now looks like:
```typescript
function isValidXkeysUsage(device: HIDDevice): boolean {
	if (device.vendorId !== XKEYS_VENDOR_ID) return false

	return !!device.collections.find((collection) => {
		if (collection.usagePage !== 12) return false

		// Check the write-length of the device is > 20
		return !!collection.outputReports?.find((report) => !!report.items?.find((item) => item.reportCount ?? 0 > 20))
	})
}
```
I have tested that this new version still works on windows, macos and linux

**Comment by michaelhatPIengineering** [comment]
Looks good, we have found that those checks always work in all our other projects as well.

Thanks

________________________________

File: packages/webhid/src/methods.ts [hunk 1]
```diff
@@ -43,7 +57,12 @@ export async function setupXkeysPanel(browserDevice: HIDDevice): Promise<XKeys>
...
 	// Wait for the device to initialize:
-	await xkeys.init()
+	try {
+		await xkeys.init()
 
-	return xkeys
+		return xkeys
+	} catch (e) {
+		await deviceWrap.close()
+		throw new Error('Failed to initialise device')
```
Comment (nytamin) [inline packages/webhid/src/methods.ts]: We should throw the original error here

**Review by nytamin — CHANGES_REQUESTED** [review]
